# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 06:45
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.BigIntegerField()),
                ('end_time', models.BigIntegerField()),
                ('mind_wander_times', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None)),
                ('distraction_times', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None)),
                ('productivity', models.SmallIntegerField()),
                ('focus', models.SmallIntegerField()),
                ('task_importance', models.SmallIntegerField()),
                ('satisfaction', models.SmallIntegerField()),
                ('mood', models.SmallIntegerField()),
                ('task_urgency', models.SmallIntegerField()),
                ('task_complexity', models.SmallIntegerField()),
                ('task_familiarity', models.SmallIntegerField()),
                ('arousal', models.SmallIntegerField()),
                ('fatigue', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
