# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 06:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksessions', '0002_auto_20171116_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksession',
            name='distraction_times',
        ),
        migrations.RemoveField(
            model_name='worksession',
            name='mind_wander_times',
        ),
        migrations.AddField(
            model_name='worksession',
            name='return_to_work_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
