# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 08:52
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksessions', '0003_auto_20171116_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='todos',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None), default=[['default todo', 'true']], size=None),
            preserve_default=False,
        ),
    ]
