# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_auto_20171113_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MindfullAttentionAwareness',
            new_name='MindfulAttentionAwareness',
        ),
    ]
