# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 05:43
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_auto_20171113_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalfatigue',
            name='questionnaire_responses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=2), size=None),
        ),
        migrations.AlterField(
            model_name='mentalfatigue',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
